/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hipico;

import javax.swing.JOptionPane;

/**
 *
 * @author Josber95
 */
public class Ganador extends javax.swing.JFrame {
    private int ticket = 0;
       
   
    
    
    
    
    
    /**
     * Creates new form Ganador
     */
    public Ganador() {
        initComponents();
        setLocationRelativeTo(null);//para que la ventana aparezca centrada
        setResizable(false);//no maximizar la ventana
        setTitle("Ganador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Ganador = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        generar_ticket = new javax.swing.JButton();
        codigo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        Bsf = new javax.swing.JLabel();
        bs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        inicio = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        Ganador2 = new javax.swing.JMenu();
        tablita = new javax.swing.JMenu();
        Prec_tablita = new javax.swing.JMenu();
        Subasta = new javax.swing.JMenu();

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        Ganador.setText("Ganardor");
        Ganador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GanadorMouseClicked(evt);
            }
        });
        jMenuBar1.add(Ganador);

        jMenu3.setText("Tablita");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Prec. Tablita");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Subasta");
        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 450, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Ticket");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Hipodromo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LA RINCONADA", "OTROS" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Carrera");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Ganador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Caballo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jTextPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane2KeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 80, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 20, 270));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 20, 210));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 10, 270));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 450, 10));

        generar_ticket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generar_ticket.setText("Generar Ticket");
        generar_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_ticketActionPerformed(evt);
            }
        });
        getContentPane().add(generar_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        codigo.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        codigo.setForeground(new java.awt.Color(255, 255, 255));
        codigo.setText("jLabel8");
        codigo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                codigoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Ganador");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, -1));

        jTextPane3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane3KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 80, -1));

        Bsf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bsf.setForeground(new java.awt.Color(0, 0, 102));
        Bsf.setText("BsF");
        getContentPane().add(Bsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 30, 30));

        bs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bs.setForeground(new java.awt.Color(255, 255, 255));
        bs.setText("jLabel8");
        getContentPane().add(bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hipico/Diapositiva2.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 672));

        jMenu6.setText("Archivo");

        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        jMenu6.add(inicio);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu6.add(salir);

        jMenuBar3.add(jMenu6);

        Ganador2.setText("Ganardor");
        Ganador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ganador2MouseClicked(evt);
            }
        });
        jMenuBar3.add(Ganador2);

        tablita.setText("Tablita");
        tablita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablitaMouseClicked(evt);
            }
        });
        jMenuBar3.add(tablita);

        Prec_tablita.setText("Prec. Tablita");
        Prec_tablita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Prec_tablitaMouseClicked(evt);
            }
        });
        jMenuBar3.add(Prec_tablita);

        Subasta.setText("Subasta");
        Subasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubastaMouseClicked(evt);
            }
        });
        jMenuBar3.add(Subasta);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GanadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GanadorMouseClicked
        Ganador obj= new Ganador();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_GanadorMouseClicked

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        pagina_inicio obj= new pagina_inicio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_inicioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void Ganador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ganador2MouseClicked
        Ganador obj= new Ganador();
        obj.setVisible(false);
        dispose();
    }//GEN-LAST:event_Ganador2MouseClicked

    private void tablitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablitaMouseClicked
        tablita obj = new tablita();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_tablitaMouseClicked

    private void Prec_tablitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Prec_tablitaMouseClicked
        Prec_tablita obj= new Prec_tablita();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Prec_tablitaMouseClicked

    private void SubastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubastaMouseClicked
        Subasta obj = new Subasta();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_SubastaMouseClicked

    private void generar_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_ticketActionPerformed
    Ticket obj= new Ticket();
    obj.setVisible(true);
    ticket ++;
        
    }//GEN-LAST:event_generar_ticketActionPerformed

    private void codigoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_codigoAncestorAdded

        String enteroString = Integer.toString(ticket); 
       codigo.setText(enteroString);
         
    }//GEN-LAST:event_codigoAncestorAdded

    private void jTextPane1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane1KeyTyped
        
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
           JOptionPane.showMessageDialog(null, "Error solo se aceptan numeros");
        
        }
        
        
        
        
    }//GEN-LAST:event_jTextPane1KeyTyped

    private void jTextPane2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane2KeyTyped
      char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
           JOptionPane.showMessageDialog(null, "Error solo se aceptan numeros");
        
        }
    }//GEN-LAST:event_jTextPane2KeyTyped

    private void jTextPane3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ganador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ganador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ganador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ganador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ganador().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bsf;
    private javax.swing.JMenu Ganador;
    private javax.swing.JMenu Ganador2;
    private javax.swing.JMenu Prec_tablita;
    private javax.swing.JMenu Subasta;
    private javax.swing.JLabel bs;
    private javax.swing.JLabel codigo;
    private javax.swing.JButton generar_ticket;
    private javax.swing.JMenuItem inicio;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenu tablita;
    // End of variables declaration//GEN-END:variables

    private void setTittle(int ticket) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
